[package]
name = "AahAI"
version = "0.1.0"
edition = "2021"

[dependencies]
aah-resource = { git="https://github.com/azurice/azur-arknights-helper" }
image = "0.25.1"
serde = "1.0.203"
serde_json = "1.0.119"
tract-core = "0.21.5"
tract-onnx = "0.21.5"
