[package]
name = "AahAI"
version = "0.1.0"
edition = "2021"

[dependencies]

image = "0.25.1"
tract-core = "0.21.5"
tract-onnx = "0.21.5"
uuid = { version = "1", features = ["v4"] }
regex = "1.5"
encoding = "0.2.33"